include('../../../../spring-config-service/Tiltfile')
include('../../../../spring-edge-service/Tiltfile')
include('../../../../spring-dispatcher-service/Tiltfile')
include('../../../../spring-order-service/Tiltfile')
include('../../../../spring-catalog-service/Tiltfile')

update_settings(max_parallel_updates=1)