apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/samutops/spring-catalog-service//k8s?ref=main

configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/samutops/catalog-service
  newTag: latest

replicas:
- count: 2
  name: catalog-service

patches:
- path: patch-env.yml
